//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjemploWebService.WSEjemplo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEjemplo.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento error del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProbarConexion", ReplyAction="*")]
        EjemploWebService.WSEjemplo.ProbarConexionResponse ProbarConexion(EjemploWebService.WSEjemplo.ProbarConexionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProbarConexionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProbarConexion", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWebService.WSEjemplo.ProbarConexionRequestBody Body;
        
        public ProbarConexionRequest() {
        }
        
        public ProbarConexionRequest(EjemploWebService.WSEjemplo.ProbarConexionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProbarConexionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public ProbarConexionRequestBody() {
        }
        
        public ProbarConexionRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProbarConexionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProbarConexionResponse", Namespace="http://tempuri.org/", Order=0)]
        public EjemploWebService.WSEjemplo.ProbarConexionResponseBody Body;
        
        public ProbarConexionResponse() {
        }
        
        public ProbarConexionResponse(EjemploWebService.WSEjemplo.ProbarConexionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProbarConexionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ProbarConexionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public ProbarConexionResponseBody() {
        }
        
        public ProbarConexionResponseBody(bool ProbarConexionResult, string error) {
            this.ProbarConexionResult = ProbarConexionResult;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : EjemploWebService.WSEjemplo.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<EjemploWebService.WSEjemplo.Service1Soap>, EjemploWebService.WSEjemplo.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EjemploWebService.WSEjemplo.ProbarConexionResponse EjemploWebService.WSEjemplo.Service1Soap.ProbarConexion(EjemploWebService.WSEjemplo.ProbarConexionRequest request) {
            return base.Channel.ProbarConexion(request);
        }
        
        public bool ProbarConexion(ref string error) {
            EjemploWebService.WSEjemplo.ProbarConexionRequest inValue = new EjemploWebService.WSEjemplo.ProbarConexionRequest();
            inValue.Body = new EjemploWebService.WSEjemplo.ProbarConexionRequestBody();
            inValue.Body.error = error;
            EjemploWebService.WSEjemplo.ProbarConexionResponse retVal = ((EjemploWebService.WSEjemplo.Service1Soap)(this)).ProbarConexion(inValue);
            error = retVal.Body.error;
            return retVal.Body.ProbarConexionResult;
        }
    }
}
